### ISSUE TITLE
Robo ZAP Connection Error 

### ISSUE THREAD

**Issue by ghost** [we45/RoboZap#1]
Hi Folks!

Firstly installed Python 2.7.13 in windows 64 bit, during installation enable "add pip to environment".
******************************************
Following steps I have taken to install the RoboZAP framework:
1. Downloaded: https://github.com/we45/RoboZap
2. After steps 1, go to robozap folder and run 
   pip install -r requirements.txt
***********************************
Using a command robot RunTest.py, I have ran my script which have two usecase
1. ZAP init
2. ZAP close
************************
Issue in ZAP close: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
************************
PFA. Please help me to resolve this.
![robot_zap_connection_error](https://user-images.githubusercontent.com/8567196/43059523-6c7c2e10-8e6a-11e8-9aa5-b3abd4697c70.png)

**Comment by abhaybhargav** [comment]
Sorry for the delay @madhu92be. Can you pull directly from pip and install it `pip install RoboZap` and give it a try again.

**Comment by ghost** [comment]
Hi Abhay

I tried in different machine. It worked for me. Still dont kw wat is the
actual issue. M sure it is about httpconnection not safely landingup.

Thanks for your support.

Regards
Madhusudana

**Comment by Sashithegreat** [comment]
Hi Abhay,
I am getting below error while running the Robot script
Importing test library 'RoboZap' failed: ModuleNotFoundError: No module named 'RoboZap'

Successfully installed RoboZap using 'pip install RoboZap' and  able to view functions defined in Robozap but while running the script, I am getting above error

Regards,
Sashi Kanth
