### ISSUE TITLE
RoboZAP lib Headless mode

### ISSUE THREAD

**Issue by ghost** [we45/RoboZap#2]
Hi

I have observed that their is no code written for zap headless mode. 

Under zap headless mode, their is a copy of gui mode. 

Please correct it and help me on this.

Thanks and Regards,
Madhusudana

**Comment by abhaybhargav** [comment]
@madhu92be Just use the keyword `start headless zap` instead of `start gui zap` and you should be good. I just checked the code. it uses the `-daemon` flag which runs headless itself.

**Comment by ghost** [comment]
Thank you @abhaybhargav
